### ISSUE TITLE
Add class .section-login

### ISSUE THREAD

**Issue by kvdmolen** [Socioneers/LiquidVoting#38]
At: http://178.62.254.91/lf/index/login.html
- Add class `.section-login` to `.section`
- In Breadcrumb (`.slot_title`) wrap word "Login" in `<li>`
- Again, remove all spaces (`&nbsp;`) and `<br>`'s

**Comment by nktc** [comment]
Done.

**Comment by kvdmolen** [comment]
Think you forgot this one:
- Add class `.section-login` to `.section`

**Comment by nktc** [comment]
Thanks, it is there now.
